### ISSUE TITLE
Vagrant up error on Windows 10

### ISSUE THREAD

**Issue by christerjohansson** [richdynamix/magestead#26]
I cloned rep into a folder, and upon Vagrant up I get this output. I tried generating keys to that folder manually with Putty Gen, but to no success.

> C:\projects\dev.pdsab.se [master]> vagrant up
> C:/projects/dev.pdsab.se/provision/magestead.rb:92:in `read': No such file or directory - C:/Users/Christer/.ssh/id_rsa.pub (Errno::ENOENT)
>         from C:/projects/dev.pdsab.se/provision/magestead.rb:92:in`block in configure'
>         from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/kernel_v2/config/vm_provisioner.rb:72:in `call'
>         from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/kernel_v2/config/vm_provisioner.rb:72:in`add_config'
>         from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/kernel_v2/config/vm.rb:317:in `provision'
>         from C:/projects/dev.pdsab.se/provision/magestead.rb:90:in`configure'
>         from C:/projects/dev.pdsab.se/Vagrantfile:17:in `block in <top (required)>'
>         from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/v2/loader.rb:37:in`call'
>         from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/v2/loader.rb:37:in `load'
>         from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/loader.rb:103:in`block (2 levels) in load'
>         from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/loader.rb:97:in `each'
>         from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/loader.rb:97:in`block in load'
>         from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/loader.rb:94:in `each'
>         from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/loader.rb:94:in`load'
>         from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/vagrantfile.rb:28:in `initialize'
>         from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:689:in`new'
>         from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:689:in `vagrantfile'
>         from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:441:in`host'
>         from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:207:in `block in action_runner'
>         from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:33:in`call'
>         from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:33:in `run'
>         from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:428:in`hook'
>         from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:671:in `unload'
>         from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:177:in`ensure in <main>'
>         from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:177:in `<main>'
> C:\projects\dev.pdsab.se [master]>

**Comment by christerjohansson** [comment]
Ok, my bad. One has to use ssh-keygen in Powershell to generate proper keys.
